services:
  spring-boot-action-app:
#    image: santoszhou/keep:spring-boot-action_${APP_VERSION}
#    image: registry.cn-hangzhou.aliyuncs.com/nirvanafire/keep:spring-boot-action_${APP_VERSION}
    image: ${DOCKER_NAMESPACE}/keep:spring-boot-action_${APP_VERSION}
    container_name: spring-boot-action-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - webnet

#  nginx:
#    image: nginx:alpine
#    container_name: nginx-proxy
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#    depends_on:
#      - spring-boot-action-app
#    networks:
#      - webnet

networks:
  webnet:
