apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-action
  template:
    metadata:
      labels:
        app: spring-boot-action
    spec:
      containers:
        - name: app
          image: spring-boot-action:1.0
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx256m"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
