apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-action
spec:
  ingressClassName: nginx
  rules:
    - host: spring.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-boot-action
                port:
                  number: 8080
