name: CI/CD with Aliyun Docker Compose

on:
  workflow_dispatch: # æ‰‹åŠ¨è§¦å‘

#on:
#  push:
#    branches:
#      - main
#    paths: # Dockerfileæˆ–è€…srcä¸‹ä»£ç å‘ç”Ÿå˜æ›´æ‰ç”Ÿæ•ˆ
#      - 'Dockerfile'
#      - 'src/**'
#      - 'docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set version
        id: version
        run: |
          VERSION="v1.0.$(date +%Y%m%d%H%M)"
          DOCKER_NAMESPACE="registry.cn-hangzhou.aliyuncs.com/nirvanafire"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "APP_VERSION=$VERSION" > .env      # ðŸ‘ˆ å†™å…¥ .env æ–‡ä»¶
          echo "DOCKER_NAMESPACE=$DOCKER_NAMESPACE" > .env      # ðŸ‘ˆ å†™å…¥ .env æ–‡ä»¶
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Aliyun Docker Registry
        run: echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALIYUN_USERNAME }} --password-stdin

      - name: Build Image
        run: docker build -t registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/keep:spring-boot-action_${{ env.VERSION }} .

      - name: Push to Aliyun
        run: docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/keep:spring-boot-action_${{ env.VERSION }}

      - name: Pull Code
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /usr/local/service/spring-boot-action
            git pull

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ".env"
          target: "/usr/local/service/spring-boot-action"

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /usr/local/service/spring-boot-action
            docker-compose pull
            docker-compose up -d