name: Build and Push Docker Image

on:
  workflow_dispatch: # æ‰‹åŠ¨è§¦å‘

#on:
#  push:
#    branches:
#      - main  # ç›‘å¬ main åˆ†æ”¯çš„æäº¤
#    paths: # Dockerfileæˆ–è€…srcä¸‹ä»£ç å‘ç”Ÿå˜æ›´æ‰ç”Ÿæ•ˆ
#      - 'Dockerfile'
#      - 'src/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set version
        id: version
        run: |
          VERSION="v1.0.$(date +%Y%m%d%H%M)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "APP_VERSION=$VERSION" > .env      # ðŸ‘ˆ å†™å…¥ .env æ–‡ä»¶
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/keep:spring-boot-action_${{ env.VERSION }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/keep:spring-boot-action_${{ env.VERSION }}
